[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
whitelist_sale = "GwiGatU1wasA7wF7LtcrxjnZJD1AdwD4yE4FTBZN4k5o"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/dante/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
